sudo: required
dist: trusty

language: php
php:
  - 7.1

services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - composer install -d=symfony

script:
  vendor/bin/simple-phpunit

after_success:
  - eval $(aws ecr get-login --region ap-southeast-2)
  - docker-compose build

deploy:
  - provider: script
    script: .travis/deploy/develop.sh
    on:
      branch: develop
  - provider: script
    script: .travis/deploy/master.sh
    on:
      branch: master

env:
  global:
  - secure: ANa8s5k5sS3WbN531xiK8u3yHhVedqv/LQUzxO89SDkhy7J+U96oEJbwZtzHyiicAl3HNimvAL8SuBhc+BBUJiEaJt6af+tP/itnktIgShbDGAb5NCaX0+99r6xVnTMjz/NSYUYAmJQ15SzFoTYAU7l00HV7nbWuRfC3AqG3Geh3i/UuXxvoDJTKgz7rdqFA5vW39+m/V6eg26g5ZrK1htcwQR7qpcBVsC+uNxC3Oi1EOL9ke1/UaX4wmVldkLmEOnHij0tbtgE9q9gNt9Gi3S23xliwS+hmDrSusL8FdXrEb4/YiB0PbhL9rRcO1xxpd4sVvJ0QMBCR4gMfwF832vbIjctA2dhBh8mm2LBLzWf3wCC9hiObrHEAsdv8n+m9bC6B9zdwRCoEiy/hbnC9QNmubVAA4BcKBcRm+e9XU49ts4DIxdlX1/DvldKc3jHa74JbgqH/Es1SSOq5IqhrOMbCuGKJzttgvwms8coB1ngP+NMRkBfUIfaoswlIA+iGGHqgeJ8dJiBhncW8UyI4y6y4eeBMkyGShmCmRaE0YCp3NDF4pbX4LHugzUDL/NeJ77V7GelOwXcTpW9Q5K/k5lSP+gcF5tV48VPVjEu9xmHPDP5W1wOpZTUSwd7nJNwROfCiZkKH8YezU0GfRV3FbVZjPs/9Kk1G1iQkw5/kfdg=
  - secure: fl37nNxDLS5ajwJ2aj21YTDN7zQnykYFM66O5qMPOXObKsaurz0+iaIi3z9vFh8NsTGuONWlz3s1O42HbVBd/iqjaJa8AapIePSYqRJckQTe3sKTOuT8Z4SH4zfbLPHkJ3TiWWjbT6SpWOfF235A1v8TXmgTKFV0XyYa73rLvEI6pxjAjlWl+wC6tGFJ6fCiLFTabYKZUtpMfLGpBPdB1bHbXi120pb3eyVks5CFTXjMjeWvjEOf4spwEvAwbe2zZvbsdNxZ0W3w16pp3+inevLRMoVh1f5FTW38iKFcDwa5radj2qztFoYJ/NaonZcSvyhkie2VsTX0RDwRk0pGtECGdmuzHwGAoC55AJN/hRn3M/46FwnT0AcYQ2EbsqJmNv0C4+JdMU2FKddZ0bRh9u4uKZx3qn7HTYrg7Oep91TBWLX/hn01agYQI2KD2IwXhXeCotugpzyF53sTGGcM8DPKSRgZvRd/ZF6ldxXzmT68Dfmx6V6jvMkOcl42ONY3TACiVUpuO9kONRcaLr3gmc7Wnran/eoqyRWw9+s+kPZHFvG4AYvD5IX5gEvNeB5TAtTckdAGDzcBWFoD+szC8Yw72I7eu7vTcdzkZ17a9sUIDf0z/89T2JkLNSw6CdczZJgBuSJYhhbP4vgQdxY1D/YddkXbWE8v5R4t0yemj5E=
