sudo: required
dist: trusty

language: php
php:
  - 7.1

services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - composer install --no-interaction -d=symfony
  - docker-compose build
  - docker-compose up -d
  - docker ps

script: docker exec php /opt/projects/docker-test/vendor/bin/phpunit -c /opt/projects/docker-test/phpunit.xml.dist

deploy:
  - provider: script
    script: chmod +x ./.travis/deploy/develop.sh && /bin/sh ./.travis/deploy/develop.sh
    on:
      branch: develop
  - provider: script
    script: chmod +x ./.travis/deploy/master.sh && /bin/sh ./.travis/deploy/master.sh
    on:
      branch: master

env:
  global:
  - secure: Fyy4A8hOpeIWlF3+nkMnDvINsiNJLbLpelqmVirjR5RcLnRAs7HowkJpCdxowFMkqAx1LhBl+N0MsZGmpHfGU7FUL4oj0QoutnWczmwfGWAf7w2Eo2zsAWCsTvQ8b84dcJjnxQXY1tadzW0CLxCwDqaAUtSUeb/Y/jZDbPSUtaGxWasXD1yreMeJ4tS1Vn3w6qZUv6IKuOSAq39faFClUBbcRoRAI7DV0bvEHPIBadeeShikna68/15fEm+v05TeteWF6z/cvrmFfq4zEkv3iH5ApVp9Ti9bMlsizFcxHbGXbA4cFx/8yGg8OpsKExo/fcwjPTDI5mmpKAz83rBm1SameeVBVt/lJjuWoUSMLzJ+5sVwGJP9VJO2Au0FX5SH+NHQ/xJu/kJ3e/rPhchpmEODGcElEyImW+tV46sLydi9SeA1E2gd24bb0YLdKgaLNWEbpGTRfxL/OQavLlGdgBY9qhupj8SZW6ZF3BNn0gtjtSwQ+lRHC7ex7HaFfsMiI8iaqXDDW3/z4sWtbzaapF2n/XqigCRRhYCfAds45B3yxKiIDBOcy2scR7hNdQIEtxZ8G5bo0UGkmM5bq7Ajy7RTR/Ip1wkuh2+jSrd/KUDY40+uZ1r2XCl6Pxt28MvexYIcdSmnnHjKYDB+NtwkNqakCYtCgOWB88QHVwm8p6s=
  - secure: NpLhsMBF1paZ1Qm3f713VYPAexNuLzYNL7cbcwkaGWsKzoksZ1t/Tmb7tTHB2O0i0/lb/YFCbZa3v60UqYUbRfKmIQ/cCBWoFF86LvH2+CuVouaInQBayD2xRlwu0Td7aEdz24sMvAFQm4m1SvQWm/WQGHekoUjVFWkedsS+3rC/4uSp24PC3mEor8+XgudYuFYsbpjXFBxDHUCGYG2UYywa+IbhEcJukAS+wi6CbydpH8Zu3+FeeFbd0GREW7kF2L4EQ0M9jZUB+W3s7QSlAsm+j66STdIP910CBX8BExejHA9SuSs5tS4cYsMSYEEap1aQIEobc1GByXOuX9Hwi6+nZ6SliKeS6KuvGJfvFcE4i7auGIflesEdyhKEQvepNKhovrIYJb9vvQv5JSIhvf2hSe7Zg/9QDVv4ORsKicjzPztnBPOzY/R9p7LmnDPi2Fr5id7kBSM5ks4q7C+mu8SReP0B3aBoskJgIEtZmq5RzN5spNWyNTUjOJZUASqBlH3qjKN/t2AEEVrhT3Ldtd5XnxHUiacK4UBi1fjunfKufwWhYCc6QHKzSZc54U+jYDBAB94S9Bh56XKuQdu/85STbRXuIhglJXMC2v355FGgClq8taII3KDNflmVFAPjwC6O8sLjEZavtC6+re4up8NfvzxS2iAJf2x48Umg1PU=
