version: '2'
networks:
    symfony:
        driver: 'bridge'

services:
  php:
      build:
          context: .
          dockerfile: .docker/php/Dockerfile
      image: ali-sarfaraz/docker-test-php
      networks:
          - symfony
  web:
      build:
          context: .
          dockerfile: .docker/web/Dockerfile
      image: ali-sarfaraz/docker-test-nginx
      ports:
          - "80:80"
      links:
          - php
      networks:
          - symfony