version: '2'
networks:
    symfony:
        driver: 'bridge'

services:
  symfony:
      build:
          context: .
          dockerfile: data/Dockerfile
      volumes:
          - ./symfony:/opt/projects/symfony
      image: ali-sarfaraz/docker-test-symfony
      networks:
          - symfony
  php:
      build:
          context: .
          dockerfile: php/Dockerfile
      image: ali-sarfaraz/docker-test-php
      volumes_from:
          - symfony
      networks:
          - symfony
  nginx:
      build:
          context: .
          dockerfile: nginx/Dockerfile
      image: ali-sarfaraz/docker-test-nginx
      ports:
          - "80:80"
      links:
          - php
      volumes_from:
          - symfony
      networks:
          - symfony